DjangoNauticBlog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from . import settings
from articles import views as article_views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.articles_list, name='home'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout")
]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.articles_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail")
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpg', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:80]+"  Read More..."

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

DjangoNauticBlog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def about(request):
    return render(request, 'about.html')


def index(request):
    return render(request, 'index.html')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


def articles_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles_list.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'article_detail.html', {'article': article})


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'article_create.html', {'form': form})

accounts/templates/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login Your Account</h1>
    <div class="form-site login">
    <form class="site-form" action="{%  url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">

    </form>

    </div>
{% endblock %}

accounts/templates/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup For New Account</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Register">

    </form>


{% endblock %}

articles/templates/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
    <h1>Create a New Article</h1>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="create_article-form">{{ form }}</div>
        <input type="submit" value="Create Article">

    </form>
    </div>
    <script src="/static/slugify.js/"></script>



{% endblock %}

articles/templates/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="article-detail">
    <div class="article">
        <div class="article-title">
            <h2 class="">{{ article.title }}</h2>
        </div>
      <hr id="underline1">
        <div class="article-thumbnail">
            <img class="blogimage img-responsive center-block thumbnail " src="{{ article.thumb.url }}">
        </div>
        <div class="article-body">
            <p class="text-justify">{{ article.body }}</p>
        </div>
        <div class="article-date">
            <p> {{ article.date }}</p>
        </div>
        <div class="article-author">
            <p class="author"><span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;&nbsp;WrittenBy:&nbsp;&nbsp;&nbsp;{{ article.author }}</p>
        </div>
    </div>
    </div>
{% endblock %}

articles/templates/articles_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Articles List</h1>
<div class="articles container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            {% for article in articles %}
        <div class="article_list">

             <div class="article_list_title">
                 <h3><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h3>
             </div>
            <div class="article_list_snippet">
                <p>{{ article.snippet }}</p>
            </div>
            <div class="article_list_date">
                <p>{{ article.date }}</p>
            </div>

            <div class="article_list_author">
                <p class="authorinlist"><span class="glyphicon glyphicon-pencil"></span>Written By:{{ article.author.username }}</p>
            </div>

        </div>
    {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>Aboutpage</h1>
    <p>django</p>

  </body>
</html>

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Articles_list</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="container-fluid">
    <nav class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-target="#mainnavbar" data-toggle="collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse mainnavbar">
            <a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic"></a>
                <ul class=" nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        <button type="submit"><a href="{% url 'articles:create' %}" class="highlight">Create New Article</a></button>
                </li>
                <li>
                     <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                       {% csrf_token %}
                         <button type="submit"><span class="glyphicon  glyphicon-log-out"></span>Logout</button>
                     </form>
                </li>



                {% else %}
                    <li><button type="submit"><a href="{% url 'accounts:login' %}"><span class="glyphicon  glyphicon-log-in"></span>&nbsp;&nbsp;Login</a></button></li>
                    <li><button type="submit"><a href="{% url 'accounts:signup' %}"><span class="glyphicon  glyphicon-plus"></span>&nbsp;&nbsp;Signup</a></button></li>
                {% endif %}
            </ul>
            </div>
        </nav>
<div class="wrapper">
{% block content %}
{% endblock %}
</div>

</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
  <h1>Homepage</h1>
  <p>Hello Django</p>

</body>
</html>